---
abstract: 'PerlIO layer for Term::ANSIColor'
author:
  - 'Masanori Hara <massa.hara at gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.59, CPAN::Meta::Converter version 2.112621'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PerlIO-via-ANSIColor
no_index:
  directory:
    - t
    - inc
requires:
  Term::ANSIColor: 0
  Test::More: 0
version: 0.05
